image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

include:
  template: Container-Scanning.gitlab-ci.yml

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE

deploy:
  stage: deploy
  script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" index.docker.io
    - docker pull $IMAGE
    - docker tag $IMAGE index.docker.io/indentcloud/terraform-gcp
    - docker push $IMAGE
  only:
    - master