image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  LOCAL_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  HUB_IMAGE: docker.io/indentcloud/cloud-deploy

include:
  template: Container-Scanning.gitlab-ci.yml

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $LOCAL_IMAGE .
    - docker push $LOCAL_IMAGE

deploy:
  stage: deploy
  script:
    - docker pull $LOCAL_IMAGE
    - docker tag $LOCAL_IMAGE $HUB_IMAGE
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" docker.io
    - docker push $HUB_IMAGE
  only:
    - master